### ISSUE TITLE
Tesr

### ISSUE THREAD

**Issue by billkamp** [bitbloxhub/graphX#1]
Is there a test program in an input sample set?

**Comment by bitbloxhub** [comment]
will work on it!

**Comment by bitbloxhub** [comment]
done.

**Comment by billkamp** [comment]
Could not at first understand the test was passed. Added a print statement. See attached.
.....
    "reltype":"follows",
    "bidirectional":False
}) == True,"delete node returned a bad value"

print("\n-------\nCongratulations: All tests passed\n=======\n")

**Comment by bitbloxhub** [comment]
put that in PR if want added
